ALTER TABLE public.admin_profiles 
  ADD COLUMN IF NOT EXISTS email TEXT,
  ADD COLUMN IF NOT EXISTS phone TEXT,
  ADD COLUMN IF NOT EXISTS access_level TEXT DEFAULT 'specific',
  ADD COLUMN IF NOT EXISTS groups TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS modules TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Active',
  ADD COLUMN IF NOT EXISTS last_login TIMESTAMPTZ;
